#!/usr/bin/env bash


function check_localflow_py() {
    if [[ -n $1 ]] && [[ -d "$1" ]] && [[ -f "$1/localflow.py" ]]; then
        return 0
    fi
    return 1
}

dir_localflow=""
# Look for localflow.py passed in the as parameter first
if [[ -n $1 ]] && check_localflow_py $1; then
    dir_localflow=$1
elif [[ -n ${LOCALFLOW_DIR} ]] && check_localflow_py ${LOCALFLOW_DIR}; then
    dir_localflow=${LOCALFLOW_DIR}
else
    echo "Could not locate Localflow directory."
fi

echo "Localflow directory: ${dir_localflow}"
#python ${dir_localflow}/localflow.py $@
